# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.0"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "pay-fee"
template_type = "Rust"

[[contracts]]
name = "auth"
template_type = "Rust"

[[contracts]]
name = "state"
template_type = "Rust"
